import '@hotwired/turbo-rails'
import 'controllers'
import './settings/jquery.min'
import './settings/isotope.min'
import './settings/owl-carousel'
import './settings/counter'
import './settings/custom'
import 'bootstrap'
import {far} from '@fortawesome/free-regular-svg-icons'
import {fas} from '@fortawesome/free-solid-svg-icons'
import {fab} from '@fortawesome/free-brands-svg-icons'
import {library} from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-free'
library.add(far, fas, fab)
